/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package io.openmessaging.consumer;

import io.openmessaging.message.Header;

/**
 * A {@code MessageReceipt} is a {@code Message} with a {@code Receipt}.
 *
 * @version OMS 1.0.0
 * @since OMS 1.0.0
 */
public interface MessageReceipt {
    /**
     * {@code OFFSET} represents this message offset in partition.
     * <p>
     *
     * @param offset The offset in the current partition, used to quickly get this message in the queue
     */
    void setOffset(long offset);

    /**
     * This method will return the {@code OFFSET}  in the partition to which the message belongs to, but the premise is
     * that the implementation of the server side is dependent on the partition or a queue-like storage mechanism.
     *
     * @return The offset of the partition to which the message belongs.
     */
    long getOffset();

    /**
     * The {@code MESSAGE_ID} header field contains a value that uniquely identify each message sent by a {@code
     * Producer}. this identifier is generated by producer.
     */
    void setMessageId(String messageId);

    /**
     * See {@link Header#setMessageId(String)}
     *
     * @return messageId
     */
    String getMessageId();
}
